# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PieceMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_move', models.CharField(max_length=10)),
            ],
        ),
    ]
